name: Maven Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        db:
          - postgresql
          - mssql
          - h2
          - db2
          - mysql
          - mariadb
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: verify
        run: ./mvnw --batch-mode verify -P${{ matrix.db }}
